"""Core domain models and exceptions for the self-healing system."""

from self_healing.core.models import (
    ActionType,
    DiagnosisReport,
    DiskUsageMetrics,
    FaultEvent,
    FaultSeverity,
    FaultType,
    IncidentRecord,
    IncidentStatus,
    MetricSnapshot,
    PolicyDecision,
    ProcessMetrics,
    ProcessState,
    RecoveryResult,
    ServiceMetrics,
    SystemCpuMetrics,
    SystemMemoryMetrics,
    SystemSnapshot,
    TargetSpec,
    VerificationResult,
    VerificationStatus,
)
from self_healing.core.exceptions import (
    ActionExecutionError,
    ConfigurationError,
    GuardrailViolationError,
    SecurityViolationError,
    SelfHealingError,
    TargetNotFoundError,
    VerificationTimeoutError,
)

__all__ = [
    "ActionType",
    "DiagnosisReport",
    "DiskUsageMetrics",
    "FaultEvent",
    "FaultSeverity",
    "FaultType",
    "IncidentRecord",
    "IncidentStatus",
    "MetricSnapshot",
    "PolicyDecision",
    "ProcessMetrics",
    "ProcessState",
    "RecoveryResult",
    "ServiceMetrics",
    "SystemCpuMetrics",
    "SystemMemoryMetrics",
    "SystemSnapshot",
    "TargetSpec",
    "VerificationResult",
    "VerificationStatus",
    "ActionExecutionError",
    "ConfigurationError",
    "GuardrailViolationError",
    "SecurityViolationError",
    "SelfHealingError",
    "TargetNotFoundError",
    "VerificationTimeoutError",
]
